### ISSUE TITLE
'TextTask' object has no attribute 'propose_prompt_wrap'

### ISSUE THREAD

**Issue by changliucoding** [princeton-nlp/tree-of-thought-llm#56]
Thank you so much for your work, it's great that tot code is open source.

I want to reproduce your performance on Text, but this problem occurred when I reproduced it. I would like to ask where I set it wrong?

**'TextTask' object has no attribute 'propose_prompt_wrap'**

My setting is **propose** **value** and **greedy**, with start index = 0 and end index = 99

I look forward from hearing you! Thanks again for this great and solid work!

**Comment by ysymyth** [comment]
Hi, please run experiments via `sh scripts/{game24, text, crosswords}/{standard_sampling, cot_sampling, bfs}.sh` in order to replicate experiment setups in the paper. `propose_prompt_wrap` is implemented for game of 24 and crosswords but not creative writing, so if you want to propose instead of sample you need to write your own prompt.
